server:
  port: 9001

spring:
  application:
    name: cloud-alibaba-payment-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #注册中心地址
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源类型
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      validation-query: select 1
      test-while-idle: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cx.entities #所有entity别名类所在包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl